name: HW7_workflow

on: [push, pull_request]

jobs:
  main:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-versions: "3.11"
      - name: Install dependencies
        run: | 
          python -m pip install --upgrade pip
          pip install --requirement requirements.txt
      - name: Upgrade syntax
        run: | 
          pyupgrade
      - name: Make autoformatting
        run: | 
          black ./
      - name: Check codestyle
        run: |
          flake8 app/main.py
